### PR TITLE
Avoid using raw types.

### PR DESCRIPTION
**Pull request by jpmossin**
The usage of raw types for type parameterized
classes makes it difficult to use the library
from Scala

### CODE REVIEW

**Comment by ened** [comment]
@jpmossin Any update on that? We'd be glad to have your changes in the project!

**Comment by jpmossin** [comment]
@ened I'm afraid I haven't had time to look much more at this. But from what I rember, removing type parameters seems difficult and would be a big change, as removing one place leads to removal somewhere else and so on. 
So I'm not sure what the conclusion should be here.

**Comment by ened** [comment]
@jpmossin got it. We'll put it on a lower priority for the moment & concentrate on the more pressing issues first.

**Comment by JJosB** [comment]
Hello,
first of all i would say that Cling is a great job!
I am not a java expert so i can't comment about the "D extends Device" and "S extends Service" parameterizations...
meanwhile:
1) is it normal that the code supplied in core manual requires the  "-Xlint:unchecked" flag?
2) could you give an example of how to deal with these parametrizations (3.2.2. Invoking an action)?
thanks
ps: goal is to prototype a windows control point with features similar to "upplay".

**Comment by ened** [comment]
@JJosB , please ask on Stackoverflow

**Pull request closed without merging**
