### PR TITLE
+Gradle Support, Bring compatibility up to java 7. Class generation compatibility still at 1.5

### PR DESCRIPTION
**Pull request by decoded4620**
…ible and easy) up to 1.7 source compatability level. Add SuppressWarnings to all rawtype, unchecked, and unused elements in the Test Suites, and Implementation so the Eclipse project is clean. 

Added Gradle Support and initial configuration files.

Work still to be done:

Need to figure out how to do this for the Android Demo Projects, as they use Android Specific resources, such as 'R.java' which is generally not included with Android Library compilation outside of Android Studio.

### CODE REVIEW

**Comment by ened** [comment]
Thanks for your contribution. The PR is too complex to merge though. 

It should be done in separate PRs. From reading into @christianbauer's Google+ posts, we will stick with Maven for the moment. Java7 might be a good idea, given that all tests pass.

**Comment by decoded4620** [comment]
Hello Sebastian,

I'll fork it from your latest and see if I can re-contribute these in a
digest-able set of smaller CL's. Currently all of my Gradle Tests pass, as
well as the maven tests. I offered a Gradle supported version, mostly
because I think Gradle offers more in general and is easier to write /
merge / manage.

Cheers!

**Comment by christianbauer** [comment]
I'm not opposed to Gradle in general, although it certainly has major problems. A move to Gradle in Cling would be fine, then we should drop the Maven build. I've considered doing this myself before but considering that we have an OK build and no particular problem to solve, I couldn't justify the investment. It's up to you guys if you want to do this.

**Comment by ened** [comment]
@decoded4620 That's good news then. It would be nice to get a updates set of PRs. (please fork of 4thline/cling, where this PR resides).

**Comment by decoded4620** [comment]
Its certainly not top priority but happy to give something lower risk like
this as a first pass.

Cheers,

Bow

**Pull request closed without merging**
